//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    startnew(): Promise<Game> {
        let url_ = this.baseUrl + "/api/game/startnew";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStartnew(_response);
        });
    }

    protected processStartnew(response: Response): Promise<Game> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Game.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Game>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    nextturn(body: Game | undefined): Promise<Game> {
        let url_ = this.baseUrl + "/api/game/nextturn";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processNextturn(_response);
        });
    }

    protected processNextturn(response: Response): Promise<Game> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Game.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Game>(null as any);
    }
}

export class Castle implements ICastle {
    hexagons?: Hexagon[] | undefined;

    constructor(data?: ICastle) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["hexagons"])) {
                this.hexagons = [] as any;
                for (let item of _data["hexagons"])
                    this.hexagons!.push(Hexagon.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Castle {
        data = typeof data === 'object' ? data : {};
        let result = new Castle();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.hexagons)) {
            data["hexagons"] = [];
            for (let item of this.hexagons)
                data["hexagons"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface ICastle {
    hexagons?: Hexagon[] | undefined;
}

export class Game implements IGame {
    id?: string;
    turnMessage?: string | undefined;
    currentTurn?: number;
    currentPlayer?: number;
    players?: Player[] | undefined;
    castle?: Castle;

    constructor(data?: IGame) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.turnMessage = _data["turnMessage"];
            this.currentTurn = _data["currentTurn"];
            this.currentPlayer = _data["currentPlayer"];
            if (Array.isArray(_data["players"])) {
                this.players = [] as any;
                for (let item of _data["players"])
                    this.players!.push(Player.fromJS(item));
            }
            this.castle = _data["castle"] ? Castle.fromJS(_data["castle"]) : <any>undefined;
        }
    }

    static fromJS(data: any): Game {
        data = typeof data === 'object' ? data : {};
        let result = new Game();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["turnMessage"] = this.turnMessage;
        data["currentTurn"] = this.currentTurn;
        data["currentPlayer"] = this.currentPlayer;
        if (Array.isArray(this.players)) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item ? item.toJSON() : <any>undefined);
        }
        data["castle"] = this.castle ? this.castle.toJSON() : <any>undefined;
        return data;
    }
}

export interface IGame {
    id?: string;
    turnMessage?: string | undefined;
    currentTurn?: number;
    currentPlayer?: number;
    players?: Player[] | undefined;
    castle?: Castle;
}

export class Hexagon implements IHexagon {
    color?: HexagonColor;
    facilities?: IFacility[] | undefined;

    constructor(data?: IHexagon) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.color = _data["color"];
            if (Array.isArray(_data["facilities"])) {
                this.facilities = [] as any;
                for (let item of _data["facilities"])
                    this.facilities!.push(IFacility.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Hexagon {
        data = typeof data === 'object' ? data : {};
        let result = new Hexagon();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["color"] = this.color;
        if (Array.isArray(this.facilities)) {
            data["facilities"] = [];
            for (let item of this.facilities)
                data["facilities"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IHexagon {
    color?: HexagonColor;
    facilities?: IFacility[] | undefined;
}

export enum HexagonColor {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
}

export class IFacility implements IIFacility {
    readonly size?: number;

    constructor(data?: IIFacility) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).size = _data["size"];
        }
    }

    static fromJS(data: any): IFacility {
        data = typeof data === 'object' ? data : {};
        let result = new IFacility();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["size"] = this.size;
        return data;
    }
}

export interface IIFacility {
    size?: number;
}

export class Player implements IPlayer {
    name?: string | undefined;
    isActive?: boolean;

    constructor(data?: IPlayer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): Player {
        data = typeof data === 'object' ? data : {};
        let result = new Player();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IPlayer {
    name?: string | undefined;
    isActive?: boolean;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}